"""Public API for the deterministic synthetic image generator."""

from .levels import (
    GENERATOR_CONTRACT_VERSION,
    LEGACY_LEVEL_SAMPLE_SHA256,
    LEVEL_CYCLE_SIZE,
    LEVEL_NAMES,
    LEVEL_TABLE,
    N_BLOCKS,
    N_LEVELS,
    SAMPLES_PER_LEVEL,
    level_block,
    level_of,
    level_start,
)
from .scene_spec import (
    AtlasRegion,
    AtlasSpec,
    Background,
    BoundingBox,
    CollisionShape,
    FlipbookClip,
    Layer,
    LightSpec,
    ObjectSpec,
    PostSpec,
    RasterSpec,
    SceneSpec,
)
from .scene_graph import (
    SceneQuery,
    check_collision,
    find_collisions,
    object_aabb,
)
from .camera import CameraSpec, aabb_in_view, screen_to_world, world_to_screen
from .layers import LayerManager
from .atlas import flipbook_region, stamp_sprite
from .particles import ParticleEmitterSpec, ParticlePool
from .physics import Contact, ContactHandler, PhysicsWorld, RayCastHit, RigidBodySpec
from .input_system import (
    InputProvider,
    InputState,
    NullInputProvider,
    PygameInputProvider,
    ReplayInputProvider,
    WebInputProvider,
)
from .game_loop import GameClock, SceneGraph
from .ui import HUD, WidgetSpec
from .tween import AnimationTrack, Keyframe, KeyframeTrack, Tween
from .tilemap import TilemapRenderer, TilemapSpec
from .replay import FrameRecord, SessionPlayer, SessionRecorder, serialize_objects
from .web_export import export_html, export_live_html
from .scene_levels import (
    SCENE_CATALOG_CONTRACT_VERSION,
    SCENE_CATALOG_CYCLE_SIZE,
    SCENE_CATALOG_SAMPLE_SHA256,
    N_ARCHETYPES,
    SAMPLES_PER_ARCHETYPE,
    SCENE_ARCHETYPES,
    SceneArchetype,
    scene_archetype_of,
    scene_seed_of,
)
from .behaviors import BEHAVIORS, Behavior, compatible_behaviors
from .scene_catalog import (
    SCENE_TRAJECTORY_SAMPLE_SHA256,
    SceneSample,
    make_scene_catalog,
    make_scene_catalog_batch,
    make_scene_trajectory,
    make_scene_trajectory_batch,
)
from .synthetic_image_generator import (
    BATCH_BACKENDS,
    BATCH_FIDELITIES,
    GPU_LEVEL_FAMILIES,
    C,
    H,
    W,
    cpu_info,
    convert_raster,
    extract_alpha,
    make_image,
    make_images,
    make_image_raster,
    make_scene,
    make_scene_raster,
)
from ._webgpu import accelerator_info
from ._version import __version__
from .wave import WAVE_LEVELS

__all__ = [
    "AnimationTrack",
    "AtlasRegion",
    "AtlasSpec",
    "Background",
    "BATCH_BACKENDS",
    "BATCH_FIDELITIES",
    "Behavior",
    "BEHAVIORS",
    "BoundingBox",
    "C",
    "CameraSpec",
    "CollisionShape",
    "Contact",
    "ContactHandler",
    "FlipbookClip",
    "FrameRecord",
    "GameClock",
    "GENERATOR_CONTRACT_VERSION",
    "GPU_LEVEL_FAMILIES",
    "H",
    "HUD",
    "InputProvider",
    "InputState",
    "Keyframe",
    "KeyframeTrack",
    "Layer",
    "LayerManager",
    "LEGACY_LEVEL_SAMPLE_SHA256",
    "LEVEL_CYCLE_SIZE",
    "LEVEL_NAMES",
    "LEVEL_TABLE",
    "LightSpec",
    "N_ARCHETYPES",
    "N_BLOCKS",
    "N_LEVELS",
    "NullInputProvider",
    "ObjectSpec",
    "ParticleEmitterSpec",
    "ParticlePool",
    "PhysicsWorld",
    "PostSpec",
    "PygameInputProvider",
    "RasterSpec",
    "RayCastHit",
    "ReplayInputProvider",
    "RigidBodySpec",
    "SAMPLES_PER_ARCHETYPE",
    "SAMPLES_PER_LEVEL",
    "SCENE_ARCHETYPES",
    "SCENE_CATALOG_CONTRACT_VERSION",
    "SCENE_CATALOG_CYCLE_SIZE",
    "SCENE_CATALOG_SAMPLE_SHA256",
    "SCENE_TRAJECTORY_SAMPLE_SHA256",
    "SceneArchetype",
    "SceneGraph",
    "SceneQuery",
    "SceneSample",
    "SceneSpec",
    "SessionPlayer",
    "SessionRecorder",
    "TilemapRenderer",
    "TilemapSpec",
    "Tween",
    "WAVE_LEVELS",
    "W",
    "WebInputProvider",
    "WidgetSpec",
    "__version__",
    "aabb_in_view",
    "accelerator_info",
    "check_collision",
    "compatible_behaviors",
    "cpu_info",
    "convert_raster",
    "export_html",
    "export_live_html",
    "extract_alpha",
    "find_collisions",
    "flipbook_region",
    "level_block",
    "level_of",
    "level_start",
    "make_image",
    "make_images",
    "make_image_raster",
    "make_scene",
    "make_scene_catalog",
    "make_scene_catalog_batch",
    "make_scene_raster",
    "make_scene_trajectory",
    "make_scene_trajectory_batch",
    "object_aabb",
    "scene_archetype_of",
    "scene_seed_of",
    "screen_to_world",
    "serialize_objects",
    "stamp_sprite",
    "world_to_screen",
]
